hash  := $(shell git rev-parse --short HEAD)
type  := mv mz
verfn := cheat-engine/www/cheat/version.js
verjs := export const RPGVERSION = "$(hash)" /* autogenerated by Makefile */
shiki := cheat-engine/www/cheat/libs/shiki.bundle.mjs
vue   := cheat-engine/www/cheat/libs/vue.js
vuetify := cheat-engine/www/cheat/libs/vuetify.js
vuetifycss := cheat-engine/www/cheat/css/vuetify.css
mdicss := cheat-engine/www/cheat/css/materialdesignicons.css
mdifonts := cheat-engine/www/cheat/fonts/materialdesignicons-webfont.woff2

.PHONY: all clean vendor $(type)

all: $(type)

vendor: $(shiki) $(vuetify) $(vue) $(vuetifycss) $(mdicss) $(mdifonts)

$(shiki):
	pnpm run vendor:shiki

$(vuetify):
	pnpm run vendor:vuetify

$(vue):
	pnpm run vendor:vue

$(vuetifycss) $(mdicss) $(mdifonts):
	pnpm run vendor:assets

clean:
	-rm -f *.zip *-latest.zip $(verfn) $(shiki) $(vuetify) $(vue) $(vuetifycss) $(mdicss)
	-rm -f cheat-engine/www/cheat/fonts/materialdesignicons-webfont.*

# tools/pack.mjs prefixes MV archives with www/ and leaves MZ archives at the
# root, so both can be extracted directly into the game root directory.
%-$(hash).zip: $(verfn) $(shiki) $(vuetify) $(vue) $(vuetifycss) $(mdicss) $(mdifonts)
	node tools/pack.mjs $* $@
	ln -s -f $@ $*-latest.zip

$(type):%:%-$(hash).zip
	@echo finished packing $@

$(verfn):
	printf '%s\n' '$(verjs)' > $(verfn)
