hash  := $(shell git rev-parse --short HEAD)
type  := mv mz
verfn := cheat-engine/www/cheat/version.js
verjs := export const RPGVERSION = "$(hash)" /* autogenerated by Makefile */
shiki := cheat-engine/www/cheat/libs/shiki.bundle.mjs
vue   := cheat-engine/www/cheat/libs/vue.js
vuetify := cheat-engine/www/cheat/libs/vuetify.js
vuetifycss := cheat-engine/www/cheat/css/vuetify.css
mdicss := cheat-engine/www/cheat/css/materialdesignicons.css
mdifonts := cheat-engine/www/cheat/fonts/materialdesignicons-webfont.woff2

# 打包时要一起打进去的源码：改动其中任意文件都应触发重新打包
src := $(shell find cheat-engine/www/cheat cheat-engine/www/_cheat_initialize -type f 2>/dev/null)

# 默认生产构建；`make dev` 会以 VUE=dev 覆盖，仅在打包期间使用开发构建
VUE ?= prod

.PHONY: all clean vendor dev prod ui-vendor $(type)

all: $(type)

vendor: $(vuetifycss) $(mdicss) $(mdifonts) ui-vendor

# 每次构建都强制按当前 VUE 重新生成 shiki / vue / vuetify，
# 避免上一次的 dev 构建被误打包进产物
ui-vendor:
	pnpm run vendor:shiki$(if $(filter dev,$(VUE)),:dev)
	pnpm run vendor:vue$(if $(filter dev,$(VUE)),:dev)
	pnpm run vendor:vuetify$(if $(filter dev,$(VUE)),:dev)
	pnpm run vendor:assets$(if $(filter dev,$(VUE)),:dev)

# dev: 使用 Vue 开发构建打包（组件告警 + Devtools），便于排查问题
dev:
	$(MAKE) VUE=dev $(type)

# prod: 使用 Vue 生产构建打包（与 make 等价）
prod:
	$(MAKE) VUE=prod $(type)

$(vuetifycss) $(mdicss) $(mdifonts):
	pnpm run vendor:assets$(if $(filter dev,$(VUE)),:dev)

clean:
	-rm -f *.zip *-latest.zip $(verfn) $(shiki) $(vuetify) $(vue) $(vuetifycss) $(mdicss)
	-rm -f cheat-engine/www/cheat/fonts/materialdesignicons-webfont.*

# tools/pack.mjs prefixes MV archives with www/ and leaves MZ archives at the
# root, so both can be extracted directly into the game root directory.
%-$(hash).zip: $(src) $(verfn) ui-vendor $(vuetifycss) $(mdicss) $(mdifonts)
	node tools/pack.mjs $* $@
	ln -s -f $@ $*-latest.zip

$(type):%:%-$(hash).zip
	@echo finished packing $@

$(verfn):
	printf '%s\n' '$(verjs)' > $(verfn)
