// 按当前 commit hash 生成 version.js（由 Makefile 调用，替代 POSIX `printf`）。
// 内容未变化时不重写文件，避免无谓的 mtime 变化。
import fs from "node:fs";

const FILE = "cheat-engine/www/cheat/version.js";
const hash = process.argv[2];

if (!hash) {
  console.error("usage: gen-version.mjs <hash>");
  process.exit(1);
}

const content = `export const RPGVERSION = "${hash}" /* autogenerated by Makefile */\n`;

let current = null;
try {
  current = fs.readFileSync(FILE, "utf8");
} catch (e) {
  // 文件不存在 → 视为需要生成
}

if (current === content) {
  console.log(`version.js unchanged (${hash})`);
} else {
  fs.writeFileSync(FILE, content);
  console.log(`version.js -> ${hash}`);
}
